
name: Live-2

on:
  workflow_run:
    workflows: ["Live-1"]
    types: [completed]

permissions:
  actions: write
  contents: read

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - run: python3 -m pip install gdown
      - run: gdown --fuzzy "https://drive.google.com/file/d/1U17yK4g1Dxu25lZpvzNUKu6LHMdTDMzg/view?usp=sharing" -O video.mp4
      - env:
          KEY: ${{ secrets.YT_STREAM_KEY }}
        run: |
          ffmpeg -re -stream_loop -1 -i video.mp4 \
          -c:v libx264 -preset veryfast -pix_fmt yuv420p \
          -c:a aac -b:a 128k \
          -f flv rtmp://a.rtmp.youtube.com/live2/$KEY
          
