
name: Live-3

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg python3-pip coreutils
          python3 -m pip install gdown

      - run: gdown 1U17yK4g1Dxu25lZpvzNUKu6LHMdTDMzg -O video.mp4

      - env:
          KEY: ${{ secrets.YT_STREAM_KEY }}
        run: |
          timeout 21550 ffmpeg -re -stream_loop -1 -i video.mp4 \
            -c:v libx264 -preset veryfast -pix_fmt yuv420p \
            -c:a aac -b:a 128k \
            -f flv "rtmp://a.rtmp.youtube.com/live2/$KEY"

      - env:
          TOKEN: ${{ github.token }}
        run: |
          curl -X POST \
          -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/live4.yml/dispatches \
          -d '{"ref":"main"}'
          
